import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {connectionInput} from '../src/lib/connection-validation';

test('Connection editions: legacy preservation, drafts, photos, versions and access control',async()=>{
  const db=new PGlite();
  try {
    await db.exec('create role anon;create role authenticated;create role service_role;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);');
    await db.exec(await readFile('supabase/migrations/202609080001_catalog.sql','utf8'));
    await db.exec(await readFile('legacy-backend/supabase/connections.sql','utf8'));
    const old=randomUUID(),admin=randomUUID(),other=randomUUID(),photo=randomUUID(),foreign=randomUUID();
    await db.query("insert into connections(id,title,theme,event_date,preacher,summary) values($1,'Legacy','Theme','2024-01-01','Preacher','Original summary')",[old]);
    await db.query("insert into connection_images(connection_id,image_url) values($1,'https://example.com/original.webp')",[old]);
    const migration=await readFile('supabase/migrations/202609080003_connections.sql','utf8');
    await db.exec(migration);await db.exec(migration);
    await db.exec(await readFile('supabase/migrations/202609090001_connection_featured.sql','utf8'));
    const linksMigration=await readFile('supabase/migrations/202609090002_connection_links.sql','utf8');
    await db.exec(linksMigration);await db.exec(linksMigration);
    const labelsMigration=await readFile('supabase/migrations/202609090003_connection_link_labels.sql','utf8');
    await db.exec(labelsMigration);await db.exec(labelsMigration);
    assert.equal((await db.query('select preacher_instagram_label from connections where id=$1',[old])).rows[0].preacher_instagram_label,'');
    assert.equal((await db.query('select preacher_instagram from connections where id=$1',[old])).rows[0].preacher_instagram,'');
    assert.equal((await db.query('select * from connection_assets')).rows.length,1);
    await db.query("insert into users(id,name,email,password_hash,role) values($1,'Admin','a@example.test','test','ADMIN'),($2,'Other','b@example.test','test','ADMIN')",[admin,other]);
    await db.query("insert into connection_assets(id,uploaded_by,storage_path) values($1,$3,'photo.webp'),($2,$4,'foreign.webp')",[photo,foreign,admin,other]);
    const draft={id:randomUUID(),title:'Encontro de teste',theme:'A paz',date:'2026-09-08',preacher:'Pregador',role:'Convidado',preacherInstagram:'https://www.instagram.com/pregador/',editionInstagram:'https://www.instagram.com/reel/teste/',summary:'Resumo completo do encontro',content:'Texto da pregação',published:false,updatedAt:null as string|null,imageIds:[photo]};
    assert.equal(connectionInput.safeParse(draft).success,true);
    assert.equal(connectionInput.safeParse({...draft,preacherInstagramLabel:'x'.repeat(81)}).success,false);
    assert.equal(connectionInput.safeParse({...draft,date:'2026-02-30'}).success,false);
    assert.equal(connectionInput.safeParse({...draft,imageIds:[photo,photo]}).success,false);
    for(const url of ['javascript:alert(1)','https://instagram.com.evil.test/profile','https://instagram.com@evil.test/profile','http://instagram.com/profile']) {
      assert.equal(connectionInput.safeParse({...draft,preacherInstagram:url}).success,false);
      assert.equal(connectionInput.safeParse({...draft,editionInstagram:url}).success,false);
    }
    assert.equal(connectionInput.safeParse({...draft,preacherInstagram:'',editionInstagram:''}).success,true);
    const save=(value:typeof draft)=>db.query('select save_connection($1::jsonb,$2::uuid[],$3::uuid)',[JSON.stringify(value),value.imageIds,admin]);
    await save(draft);
    const labelVersion=(await db.query<{value:string}>('select updated_at::text as value from connections where id=$1',[draft.id])).rows[0].value;
    await db.query('select save_connection($1::jsonb,$2::uuid[],$3::uuid)',[JSON.stringify({...draft,updatedAt:labelVersion,preacherInstagramLabel:'Siga o Marcelo',editionInstagramLabel:'Veja no Instagram'}),draft.imageIds,admin]);
    assert.deepEqual((await db.query('select preacher_instagram_label,edition_instagram_label from connections where id=$1',[draft.id])).rows[0],{preacher_instagram_label:'Siga o Marcelo',edition_instagram_label:'Veja no Instagram'});
    assert.deepEqual((await db.query('select preacher_instagram,edition_instagram from connections where id=$1',[draft.id])).rows[0],{preacher_instagram:draft.preacherInstagram,edition_instagram:draft.editionInstagram});
    assert.equal((await db.query('select id from connections where published')).rows.length,0);
    const version=async()=>(await db.query<{value:string}>('select updated_at::text as value from connections where id=$1',[draft.id])).rows[0].value;
    draft.updatedAt=await version();draft.published=true;
    await assert.rejects(save({...draft,imageIds:[foreign]}),{code:'22023'});
    await save(draft);
    assert.equal((await db.query('select id from connections where published')).rows.length,1);
    await assert.rejects(save(draft),{code:'40001'});
    const feature=(id:string,selected:boolean,expected:string,actor=admin)=>db.query('select set_connection_featured($1,$2,$3,$4)',[id,selected,expected,actor]);
    await assert.rejects(feature(old,true,(await db.query<{value:string}>('select updated_at::text as value from connections where id=$1',[old])).rows[0].value),{code:'22023'});
    await assert.rejects(feature(draft.id,true,await version(),randomUUID()),{code:'42501'});
    await feature(draft.id,true,await version());
    draft.updatedAt=await version();draft.preacherInstagram='';draft.editionInstagram='';await save(draft);
    assert.deepEqual((await db.query('select preacher_instagram,edition_instagram,featured from connections where id=$1',[draft.id])).rows[0],{preacher_instagram:'',edition_instagram:'',featured:true});
    await assert.rejects(save(draft),{code:'40001'});
    await db.query('update connections set published=true where id=$1',[old]);
    const oldVersion=async()=>(await db.query<{value:string}>('select updated_at::text as value from connections where id=$1',[old])).rows[0].value;
    await feature(old,true,await oldVersion());
    assert.deepEqual((await db.query('select id from connections where featured')).rows,[{id:old}]);
    assert.equal((await db.query('select id from connections where published order by featured desc,event_date desc limit 1')).rows[0].id,old);
    await feature(old,false,await oldVersion());
    assert.equal((await db.query('select id from connections where featured')).rows.length,0);
    await feature(old,true,await oldVersion());
    await db.query('update connections set active=false where id=$1',[old]);
    assert.equal((await db.query('select id from connections where featured')).rows.length,0);
    await feature(draft.id,true,await version());
    draft.updatedAt=await version();draft.imageIds=[];draft.published=false;await save(draft);
    assert.equal((await db.query('select id from connection_assets where connection_id=$1 and active',[draft.id])).rows.length,0);
    assert.equal((await db.query('select id from connections where featured')).rows.length,0);
    await db.query('update connections set active=false where id=$1',[draft.id]);
    draft.updatedAt=await version();await assert.rejects(save(draft),{code:'P0002'});
    await db.exec('set role anon');
    await assert.rejects(db.query('select * from connections'),/permission denied/);
    await assert.rejects(save(draft),/permission denied/);
  }finally{await db.close();}
});
