import assert from 'node:assert/strict';

export async function testConnections({page,context,origin,photos,output}) {
  assert.equal((await fetch(`${origin}/api/admin/connections`)).status,401);
  assert.equal((await fetch(`${origin}/api/admin/connections/uploads`,{method:'POST',headers:{origin}})).status,401);
  assert.equal((await context.request.post(`${origin}/api/admin/connections`,{headers:{origin:'https://wrong.example'},data:{}})).status(),403);
  await page.goto(`${origin}/admin/conexao`);
  await page.getByRole('button',{name:'Nova edição',exact:true}).click();
  await page.getByLabel('Título da edição *',{exact:true}).fill('Conexão de integração');
  await page.getByLabel('Tema *',{exact:true}).fill('A paz de Cristo');
  await page.getByLabel('Data do evento *',{exact:true}).fill('2026-09-08');
  await page.getByLabel('Pregador convidado *',{exact:true}).fill('Pregador de teste');
  await page.getByLabel('Resumo *',{exact:true}).fill('Resumo da edição cadastrada no teste completo.');
  await page.getByLabel('Conteúdo completo da pregação',{exact:true}).fill('Primeiro parágrafo.\nSegundo parágrafo. <img src=x onerror=alert(1)>');
  await page.getByLabel('Fotos do evento',{exact:true}).setInputFiles(photos);
  await page.getByRole('button',{name:'Remover foto 2',exact:true}).waitFor();
  await page.getByRole('button',{name:'Salvar edição',exact:true}).click();
  await page.getByText('Edição salva no banco de dados.',{exact:true}).waitFor();
  await page.reload();
  await page.getByText('Rascunho',{exact:true}).waitFor();
  assert.equal((await (await fetch(`${origin}/api/connections`)).json()).total,0);
  let list=await (await context.request.get(`${origin}/api/admin/connections`)).json();
  assert.equal(list.items[0].images.length,2);
  const first=list.items[0].images[0].id;
  await page.getByRole('button',{name:'Editar',exact:true}).click();
  await page.getByRole('button',{name:'Mover foto 2 para antes',exact:true}).click();
  await page.getByLabel('Publicar esta edição',{exact:true}).check();
  await page.screenshot({path:`${output}/connection-admin-mobile.png`});
  assert.equal(await page.evaluate(()=>document.querySelector('dialog').scrollWidth>document.querySelector('dialog').clientWidth),false);
  await page.getByRole('button',{name:'Salvar edição',exact:true}).click();
  await page.getByText('Edição salva no banco de dados.',{exact:true}).waitFor();
  list=await (await fetch(`${origin}/api/connections`)).json();
  assert.equal(list.total,1);assert.notEqual(list.items[0].images[0].id,first);
  assert.equal((await (await fetch(`${origin}/api/connections?year=2025`)).json()).total,0);
  assert.equal((await (await fetch(`${origin}/api/connections?year=2026`)).json()).total,1);
  const customer=await context.newPage();
  await customer.goto(`${origin}/conexao`);
  await customer.locator('.card-conexao-destaque').waitFor();
  await customer.locator('.preloader-visivel').waitFor({state:'hidden'});
  await customer.locator('.card-conexao-destaque').scrollIntoViewIfNeeded();
  await customer.screenshot({path:`${output}/connection-public-desktop.png`});
  await customer.getByText('Ver pregação completa',{exact:true}).click();
  await customer.locator('.conteudo-pregacao').waitFor();
  assert.equal(await customer.locator('.conteudo-pregacao img').count(),0);
  assert.ok((await customer.locator('.conteudo-pregacao').textContent()).includes('<img src=x'));
  await customer.getByRole('button',{name:'Fechar',exact:true}).click();
  await customer.setViewportSize({width:390,height:844});
  await customer.locator('.nav-links').waitFor({state:'hidden'});
  await customer.screenshot({path:`${output}/connection-public-mobile.png`});
  assert.equal(await customer.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  page.once('dialog',dialog=>dialog.accept());
  await page.getByRole('button',{name:'Arquivar',exact:true}).click();
  await page.getByText('Edição arquivada.',{exact:true}).waitFor();
  assert.equal((await (await fetch(`${origin}/api/connections`)).json()).total,0);
  console.log('PASS connections: protected routes, draft, upload, persistence, publish, reorder, public gallery, year filter, text safety, archive and mobile');
}
