import assert from 'node:assert/strict';

export async function testConnections({page,context,origin,photos,output}) {
  assert.equal((await fetch(`${origin}/api/admin/connections`)).status,401);
  assert.equal((await fetch(`${origin}/api/admin/connections/uploads`,{method:'POST',headers:{origin}})).status,401);
  assert.equal((await context.request.post(`${origin}/api/admin/connections`,{headers:{origin:'https://wrong.example'},data:{}})).status(),403);
  await page.goto(`${origin}/admin/conexao`);
  await page.getByRole('button',{name:'Nova edição',exact:true}).click();
  await page.getByLabel('Título da edição *',{exact:true}).fill('Conexão de integração');
  await page.getByLabel('Tema *',{exact:true}).fill('A paz de Cristo');
  await page.getByLabel('Data do evento *',{exact:true}).fill('2026-09-08');
  await page.getByLabel('Pregador convidado *',{exact:true}).fill('Pregador de teste');
  const profile='https://www.instagram.com/pregador_teste/';
  const edition='https://www.instagram.com/reel/edicao_teste/';
  await page.getByLabel('Instagram do pregador',{exact:true}).fill(profile);
  await page.getByLabel('Link da edição no Instagram',{exact:true}).fill(edition);
  await page.getByLabel('Resumo *',{exact:true}).fill('Resumo da edição cadastrada no teste completo.');
  await page.getByLabel('Conteúdo completo da pregação',{exact:true}).fill('Primeiro parágrafo.\nSegundo parágrafo. <img src=x onerror=alert(1)>');
  await page.getByLabel('Fotos do evento',{exact:true}).setInputFiles(photos);
  await page.getByRole('button',{name:'Remover foto 2',exact:true}).waitFor();
  await page.getByRole('button',{name:'Salvar edição',exact:true}).click();
  await page.getByText('Edição salva no banco de dados.',{exact:true}).waitFor();
  await page.reload();
  await page.getByText('Rascunho',{exact:true}).waitFor();
  assert.equal((await (await fetch(`${origin}/api/connections`)).json()).total,0);
  let list=await (await context.request.get(`${origin}/api/admin/connections`)).json();
  assert.equal(list.items[0].images.length,2);
  assert.equal(list.items[0].preacherInstagram,profile);
  assert.equal(list.items[0].editionInstagram,edition);
  const first=list.items[0].images[0].id;
  await page.getByRole('button',{name:'Editar',exact:true}).click();
  assert.equal(await page.getByLabel('Instagram do pregador',{exact:true}).inputValue(),profile);
  assert.equal(await page.getByLabel('Link da edição no Instagram',{exact:true}).inputValue(),edition);
  await page.getByRole('button',{name:'Mover foto 2 para antes',exact:true}).click();
  await page.getByLabel('Publicar esta edição',{exact:true}).check();
  await page.screenshot({path:`${output}/connection-admin-mobile.png`});
  assert.equal(await page.evaluate(()=>document.querySelector('dialog').scrollWidth>document.querySelector('dialog').clientWidth),false);
  await page.getByRole('button',{name:'Salvar edição',exact:true}).click();
  await page.getByText('Edição salva no banco de dados.',{exact:true}).waitFor();
  list=await (await fetch(`${origin}/api/connections`)).json();
  assert.equal(list.total,1);assert.notEqual(list.items[0].images[0].id,first);
  assert.equal((await (await fetch(`${origin}/api/connections?year=2025`)).json()).total,0);
  assert.equal((await (await fetch(`${origin}/api/connections?year=2026`)).json()).total,1);
  await page.getByRole('button',{name:'Definir como destaque',exact:true}).click();
  await page.getByText('Edição definida como destaque.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Remover destaque',exact:true}).waitFor();
  assert.equal((await (await fetch(origin+'/api/connections')).json()).items[0].featured,true);
  const secondId=crypto.randomUUID();
  const second=await context.request.post(origin+'/api/admin/connections',{headers:{origin},data:{id:secondId,title:'Segunda edição',theme:'Tema de teste',date:'2025-01-01',preacher:'Outro pregador',role:'Convidado',summary:'Resumo da segunda edição para testar o botão Ler mais.',content:'Conteúdo da segunda edição',published:true,imageIds:[],updatedAt:null}});
  assert.equal(second.status(),201);
  const customer=await context.newPage();
  await customer.goto(`${origin}/conexao`);
  await customer.locator('.card-conexao-destaque').waitFor();
  await customer.locator('.preloader-visivel').waitFor({state:'hidden'});
  await customer.locator('.card-conexao-destaque').scrollIntoViewIfNeeded();
  await customer.screenshot({path:`${output}/connection-public-desktop.png`});
  const open=customer.getByRole('button',{name:'Ver pregação completa',exact:true});
  await open.scrollIntoViewIfNeeded();
  assert.equal(await open.evaluate(el=>getComputedStyle(el).cursor),'pointer');
  const scrollBefore=await customer.evaluate(()=>scrollY);
  await open.click();
  await customer.locator('.conteudo-pregacao').waitFor();
  const modal=customer.getByRole('dialog',{name:'Conexão de integração',exact:true});
  assert.equal(await modal.evaluate(el=>el.matches(':modal')),true);
  assert.ok(Math.abs(await customer.evaluate(()=>scrollY)-scrollBefore)<2);
  assert.ok((await modal.boundingBox()).y>=0);
  assert.equal(await modal.getByRole('link',{name:'Instagram do pregador',exact:true}).getAttribute('href'),profile);
  assert.equal(await modal.getByRole('link',{name:'Edição no Instagram',exact:true}).getAttribute('href'),edition);
  assert.equal(await modal.getByRole('link',{name:'Edição no Instagram',exact:true}).getAttribute('target'),'_blank');
  await customer.screenshot({path:`${output}/connection-modal-desktop.png`,animations:'disabled'});
  assert.equal(await customer.locator('.conteudo-pregacao img').count(),0);
  assert.ok((await customer.locator('.conteudo-pregacao').textContent()).includes('<img src=x'));
  await customer.getByRole('button',{name:'Fechar',exact:true}).click();
  await modal.waitFor({state:'hidden'});
  assert.equal(await open.evaluate(el=>el===document.activeElement),true);
  assert.ok(Math.abs(await customer.evaluate(()=>scrollY)-scrollBefore)<2);
  await open.press('Enter');
  await modal.waitFor();
  await customer.keyboard.press('Escape');
  await modal.waitFor({state:'hidden'});
  await customer.setViewportSize({width:390,height:844});
  await customer.locator('.nav-links').waitFor({state:'hidden'});
  await customer.screenshot({path:`${output}/connection-public-mobile.png`});
  assert.equal(await customer.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  const readMore=customer.getByRole('button',{name:'Ler mais →',exact:true});
  await readMore.scrollIntoViewIfNeeded();
  assert.equal(await readMore.evaluate(el=>getComputedStyle(el).cursor),'pointer');
  await readMore.click();
  const secondModal=customer.getByRole('dialog',{name:'Segunda edição',exact:true});
  await secondModal.waitFor();
  assert.equal(await secondModal.getByRole('link').count(),0);
  assert.ok((await secondModal.boundingBox()).y>=0);
  await customer.getByRole('button',{name:'Fechar',exact:true}).click();
  await secondModal.waitFor({state:'hidden'});
  await open.click();
  await modal.waitFor();
  await customer.screenshot({path:`${output}/connection-modal-mobile.png`,animations:'disabled'});
  assert.equal(await modal.evaluate(el=>el.scrollWidth>el.clientWidth),false);
  await modal.click({position:{x:2,y:2}});
  await modal.waitFor({state:'hidden'});
  await customer.emulateMedia({reducedMotion:'reduce'});
  await open.click();
  await modal.waitFor();
  assert.equal(await modal.locator('.modal-conexao').evaluate(el=>getComputedStyle(el).animationName),'none');
  await customer.keyboard.press('Escape');
  await modal.waitFor({state:'hidden'});
  page.once('dialog',dialog=>dialog.accept());
  await page.locator('.card-edicao').filter({has:page.getByRole('heading',{name:'Conexão de integração',exact:true})}).getByRole('button',{name:'Arquivar',exact:true}).click();
  await page.getByText('Edição arquivada.',{exact:true}).waitFor();
  const remaining=(await (await context.request.get(origin+'/api/admin/connections')).json()).items.find(item=>item.id===secondId);
  assert.equal((await context.request.delete(origin+'/api/admin/connections/'+secondId,{headers:{origin},data:{updatedAt:remaining.updatedAt}})).status(),200);
  assert.equal((await (await fetch(`${origin}/api/connections`)).json()).total,0);
  console.log('PASS connections: protected routes, draft, upload, persistence, publish, reorder, public gallery, year filter, text safety, archive and mobile');
}
