/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import {useEffect,useMemo,useState} from "react";
import {Connection,connectionSeed,formatConnectionDate} from "@/lib/connections";

const key="pp_conexoes";
const IconPhoto=()=> <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" style={{width:36,height:36,stroke:"var(--areia)"}}><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>;
const Photo=({url,alt}:{url?:string;alt:string})=>url?<img src={url} alt={alt}/>:<div className="foto-placeholder"><IconPhoto/><strong>Foto do evento</strong></div>;
const Star=()=> <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8" strokeLinecap="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>;
const Person=()=> <div className="pregador-avatar"><svg viewBox="0 0 24 24" fill="none" strokeWidth="1.5" strokeLinecap="round"><path d="M20 21a8 8 0 0 0-16 0"/><circle cx="12" cy="7" r="4"/></svg></div>;
const Calendar=()=> <svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8" strokeLinecap="round"><rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></svg>;

export default function ConnectionsView(){
 const [all,setAll]=useState<Connection[]>(connectionSeed); const [year,setYear]=useState("todas"); const [selected,setSelected]=useState<Connection|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(key); if(raw)setAll(JSON.parse(raw)); else localStorage.setItem(key,JSON.stringify(connectionSeed));}catch{}},[]);
 useEffect(()=>{document.body.style.overflow=selected?"hidden":""; const fn=(e:KeyboardEvent)=>e.key==="Escape"&&setSelected(null);document.addEventListener("keydown",fn);return()=>{document.body.style.overflow="";document.removeEventListener("keydown",fn)}},[selected]);
 const published=useMemo(()=>all.filter(c=>c.published).sort((a,b)=>b.date.localeCompare(a.date)),[all]);
 const years=[...new Set(published.map(c=>c.date.slice(0,4)))]; const shown=year==="todas"?published:published.filter(c=>c.date.startsWith(year)); const latest=shown[0];
 return <>
  <div className="filtro-edicoes"><span>Filtrar:</span><button className={`btn-filtro ${year==="todas"?"ativo":""}`} onClick={()=>setYear("todas")}>Todas</button>{years.map(y=><button key={y} className={`btn-filtro ${year===y?"ativo":""}`} onClick={()=>setYear(y)}>{y}</button>)}</div>
  {latest&&<a className="card-conexao-destaque" href="#" onClick={e=>{e.preventDefault();setSelected(latest)}}><div className="card-destaque-foto"><span className="tag-mais-recente">Mais recente</span><Photo url={latest.photos[0]} alt={latest.title}/></div><div className="card-destaque-corpo"><span className="rotulo">Edição em destaque</span><h2>{latest.title}</h2><span className="tema-tag"><Star/>{latest.theme}</span><div className="pregador-info"><Person/><div className="pregador-texto"><strong>{latest.preacher}</strong><span>{latest.role||"Pregador convidado"}</span></div></div><p>{latest.summary}</p><div className="card-meta"><span><Calendar/>{formatConnectionDate(latest.date)}</span>{latest.photos.length>0&&<span>{latest.photos.length} fotos</span>}</div><span className="btn btn-primario" style={{alignSelf:"flex-start"}}>Ver pregação completa</span></div></a>}
  <div className="grade-conexoes">{shown.slice(1).map(c=><a key={c.id} className="card-conexao" href="#" onClick={e=>{e.preventDefault();setSelected(c)}}><div className="card-conexao-foto"><Photo url={c.photos[0]} alt={c.title}/></div><div className="card-conexao-corpo"><span className="rotulo">Edição Conexão</span><h3>{c.title}</h3><span className="tema-tag"><Star/>{c.theme}</span><p>{c.summary}</p><div className="card-conexao-rodape"><div className="card-meta"><span><Calendar/>{formatConnectionDate(c.date)}</span></div><span style={{fontSize:".82rem",color:"var(--terracota)",fontWeight:600}}>Ler mais →</span></div></div></a>)}</div>
  {!shown.length&&<div style={{textAlign:"center",padding:"60px 0",color:"var(--espresso-60)"}}><p style={{fontSize:"1.05rem"}}>Nenhuma edição publicada ainda.</p><p>Acompanhe nossas redes sociais para saber quando a próxima Conexão acontece!</p></div>}
  <div className={`modal-conexao-overlay ${selected?"":"oculto"}`} onClick={e=>e.currentTarget===e.target&&setSelected(null)}>{selected&&<div className="modal-conexao"><div className="modal-conexao-foto"><Photo url={selected.photos[0]} alt={selected.title}/><button className="modal-conexao-fechar" onClick={()=>setSelected(null)} aria-label="Fechar"><svg viewBox="0 0 24 24" fill="none" strokeWidth="2" strokeLinecap="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div><div className="modal-conexao-corpo"><span className="rotulo">Edição Conexão · {formatConnectionDate(selected.date)}</span><h2>{selected.title}</h2><span className="tema-tag" style={{display:"inline-flex",marginBottom:6}}><Star/>{selected.theme}</span><div className="pregador-info"><Person/><div className="pregador-texto"><strong>{selected.preacher}</strong><span>{selected.role||"Pregador convidado"}</span></div></div><div className="conteudo-pregacao" dangerouslySetInnerHTML={{__html:selected.content}}/>{selected.photos.slice(1).length>0&&<><h4 style={{marginTop:28,marginBottom:4,fontSize:"1rem"}}>Fotos do evento</h4><div className="galeria-modal">{selected.photos.slice(1).map((p,i)=><div className="galeria-modal-foto" key={p+i}><img src={p} alt="Foto do evento"/></div>)}</div></>}</div></div>}</div>
 </>;
}
